### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by songxiaoguo** [JihuaPeng/KTPFormer#1]
Sorry to bother you, and I appreciate your work, I would like to ask when the code will be released.

**Comment by DanielBUBU** [comment]
Same

> Sorry to bother you, and I appreciate your work, I would like to ask when the code will be released.

**Comment by lllluy** [comment]
> Sorry to bother you, and I appreciate your work, I would like to ask when the code will be released.

1

**Comment by JihuaPeng** [comment]
already updated.
