### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Zhiying-Li-dot** [JihuaPeng/KTPFormer#3]
Dear author, 
Your work KPTformer is of great significance to the task of 3D human pose estimation. Could you please release your code so that I can learn from it?

**Comment by zdpyz** [comment]
Dear author,
Your work KPTformer is of great significance to the task of 3D human pose estimation. Could you please release your code so that I can learn from it?

**Comment by JihuaPeng** [comment]
already updated.

**Comment by zdpyz** [comment]
Dear Peng:
&nbsp; &nbsp; &nbsp; &nbsp; Now I have a problem. The PCK and AUC indicators in the mpii_3dhp_evaluation_sequencewise.csv file generated by matlab have TestSeq1-6. Which one should I choose? Or do we average all six of them?



---Original---
From: "Jihua ***@***.***&gt;
Date: Wed, Jul 17, 2024 15:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JihuaPeng/KTPFormer] Code (Issue #3)




 
Closed #3 as completed.
